# publisher.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "publisher"
        dapr.io/app-port: "6500"
    spec:
      containers:
      - name: publisher
        image: publisher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6500
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
spec:
  selector:
    app: publisher
  ports:
  - port: 80
    targetPort: 6500
  type: ClusterIP