# subscriber.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subscriber"
        dapr.io/app-port: "6501"
    spec:
      containers:
      - name: subscriber
        image: subscriber:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6501
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
spec:
  selector:
    app: subscriber
  ports:
  - port: 80
    targetPort: 6501
  type: ClusterIP