apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderpubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: redis-secrets 
      key: redis-host
auth:
  secretStore: local-secrets